#############################################################################
# Makefile for building: TCPEncryptedClient
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  TCPEncryptedClient.pro
# Template: app
# Command: /usr/lib64/qt5/bin/qmake -o Makefile TCPEncryptedClient.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++1z -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -Iinclude -I/usr/include/qt5 -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I. -I/usr/lib64/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib64/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib64/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib64/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = TCPEncryptedClient1.0.0
DISTDIR = /home/danta/TCPEncryptedClient/.tmp/TCPEncryptedClient1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -lssl -lcrypto /usr/lib64/libQt5Gui.so /usr/lib64/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		src/cipher.cpp 
OBJECTS       = main.o \
		cipher.o
DIST          = TCPEncryptedClient.pro include/cipher.h main.cpp \
		src/cipher.cpp
QMAKE_TARGET  = TCPEncryptedClient
DESTDIR       = 
TARGET        = TCPEncryptedClient


first: all
####### Build rules

TCPEncryptedClient:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: TCPEncryptedClient.pro /usr/lib64/qt5/mkspecs/linux-g++/qmake.conf
		TCPEncryptedClient.pro
	$(QMAKE) -o Makefile TCPEncryptedClient.pro

TCPEncryptedClient.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile TCPEncryptedClient.pro

qmake_all: FORCE


all: Makefile TCPEncryptedClient

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents include/cipher.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp src/cipher.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib64/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++1z -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib64/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean 

####### Compile

main.o: main.cpp include/cipher.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

cipher.o: src/cipher.cpp include/cipher.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cipher.o src/cipher.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/TCPEncryptedClient/bin || mkdir -p $(INSTALL_ROOT)/opt/TCPEncryptedClient/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/TCPEncryptedClient/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/TCPEncryptedClient/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/TCPEncryptedClient/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/TCPEncryptedClient/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:
